version: '3.3'

services:
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: bitnami/redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

  user-api:
    restart: always
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - API_HOST=0.0.0.0
      - API_PORT
      - API_SESSION_SECRET
      - API_SESSION_MAX_AGE
      - API_SESSION_SECURE
      - API_CORS_ORIGINS
      - DB_HOST=database
      - DB_PORT
      - DB_URL=postgresql://$DB_USER:$DB_PASS@database:$DB_PORT/$DB_NAME?schema=$DB_SCHEMA
      - REDIS_PASS
      - REDIS_HOST=redis
      - REDIS_PORT
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - backend
    depends_on:
      - database
      - redis

networks:
  backend:

volumes:
  postgres_data: